#!/bin/bash
set -e
PATH_TMP="/tmp/walnutpi1b-patch"

cp $PATH_TMP/config-6.1.31 /boot
cp $PATH_TMP/sun50i-h616-walnutpi-1b.dtb /boot
cp $PATH_TMP/sun50i-h616-walnutpi-1b-emmc.dtb /boot
cp $PATH_TMP/boot.cmd /boot
cp $PATH_TMP/boot.scr /boot

if [ ! -f /boot/uInitrd ]; then
    update-initramfs -uv -k 6.1.31
fi

if [ -f  /boot/overlays/sun50i-h616-pwm1* ]; then
    sudo rm /boot/overlays/sun50i-h616-pwm*
fi
