#!/bin/sh

set -e

case "$1" in
    configure)
        # create bluetooth group if not already present
        if ! getent group bluetooth > /dev/null; then
            addgroup --quiet --system bluetooth
        fi

        # reload dbus config file
        if [ -x /etc/init.d/dbus ]; then
            invoke-rc.d dbus force-reload || true
        fi

        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/bluetooth/network.service 3.30-1\~ bluez-utils -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/serial.service 3.30-1\~ bluez-utils -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/input.service 3.30-1\~ bluez-utils -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/bluez-hcid.conf 3.7-1\~ bluez-utils -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/rfcomm.conf 5.21-2\~ bluez -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/serial.conf 5.21-2\~ bluez -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/audio.conf 5.21-2\~ bluez -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/proximity.conf 5.50-1\~ bluez -- "$@"
dpkg-maintscript-helper mv_conffile /etc/dbus-1/system.d/bluez-hcid.conf /etc/dbus-1/system.d/bluetooth.conf 3.7-1 bluez -- "$@"
dpkg-maintscript-helper mv_conffile /etc/modprobe.d/bluez /etc/modprobe.d/bluez.conf 4.42-1 bluez -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/bluetooth" ]; then
		update-rc.d bluetooth defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native bluetooth $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'bluetooth.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'bluetooth.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'bluetooth.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'bluetooth.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'bluetooth.service' >/dev/null || true
	fi
fi
# End automatically added section

