#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "remove" ] && [ -x "/etc/init.d/bluetooth" ] ; then
	chmod -x "/etc/init.d/bluetooth" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d bluetooth remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/bluetooth/network.service 3.30-1\~ bluez-utils -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/serial.service 3.30-1\~ bluez-utils -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/input.service 3.30-1\~ bluez-utils -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/bluez-hcid.conf 3.7-1\~ bluez-utils -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/rfcomm.conf 5.21-2\~ bluez -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/serial.conf 5.21-2\~ bluez -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/audio.conf 5.21-2\~ bluez -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bluetooth/proximity.conf 5.50-1\~ bluez -- "$@"
dpkg-maintscript-helper mv_conffile /etc/dbus-1/system.d/bluez-hcid.conf /etc/dbus-1/system.d/bluetooth.conf 3.7-1 bluez -- "$@"
dpkg-maintscript-helper mv_conffile /etc/modprobe.d/bluez /etc/modprobe.d/bluez.conf 4.42-1 bluez -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'bluetooth.service' >/dev/null || true
	fi
fi
# End automatically added section
