from .YOLO11 import YOLO11_CLS, YOLO_RESULT_CLS
from .YOLO11 import YOLO11_DET, YOLO_RESULT_DET
from .FACE_DETECT import FACE_DETECT, FACE_DETECT_RESULT
from .PERSON_DETECT import PERSON_DETECT, PERSON_DETECT_RESULT
from .PERSON_KEYPOINT import PERSON_KEYPOINT, PERSON_KEYPOINT_RESULT
from .FALL_DETECT import FALL_DETECT, FALL_DETECT_RESULT
from .HAND_DETECT import HAND_DETECT, HAND_DETECT_RESULT
from .HAND_KEYPOINT import HAND_KEYPOINT, HAND_KEYPOINT_RESULT
from .HAND_KEYPOINT_CLS import HAND_KEYPOINT_CLS, HAND_KEYPOINT_CLS_RESULT
from .OCR import OCR_DET, OCR_DET_RESULT, OCR_REC, OCR_RESULT, OCR
