#!/bin/bash

if [ "$1" = "remove" ]  ; then
    if [[ -d "/usr/lib/walnutpi/set-lcd" ]]; then
        echo "clean the git project"
        rm -r /usr/lib/walnutpi/set-lcd
    fi
fi

systemctl stop set_lcd_choose.service
systemctl disable set_lcd_choose.service