#!/bin/bash

set -e

cd /usr/lib/walnutpi

echo "aw.gpio"
pip3 --no-cache-dir install -e gpioc/ 

echo "Adafruit_Blinka"
pip3 --no-cache-dir install -e Adafruit_Blinka/ 


echo "gpioc"
cd gpioc/
./install


echo -e "\nready"