#!/bin/bash

set -e

cd /usr/lib/walnutpi

echo "aw.gpio"
pip3 --no-cache-dir install -e aw.gpio/ 

echo "Adafruit_Blinka"
pip3 --no-cache-dir install -e Adafruit_Blinka/ 


echo "WiringPi"
cd WiringPi/
./build


echo -e "\nready"