#!/bin/bash

set -e

cd /usr/lib/walnutpi

echo "WiringPi"
cd WiringPi/
./build


cd /usr/lib/walnutpi

echo "gpioc"
pip3 --no-cache-dir install -e gpioc/ 

echo "Adafruit_Blinka"
pip3 --no-cache-dir install -e Adafruit_Blinka/ 


cd /usr/lib/walnutpi

echo "gpioc"
cd gpioc/
./install


echo -e "\nready"