#!/bin/bash

Board_model=$(tr -d '\0' </proc/device-tree/model)
if [ $Board_model == "walnutpi-2b" ]; then
    rfkill unblock all
    PATH_WAKE="/proc/bluetooth/sleep/btwrite"
    while true; do
        if [ -f $PATH_WAKE ]; then
            echo 1 >${PATH_WAKE}
            break
        fi
        sleep 1
    done
fi

hciattach -s 1500000 /dev/ttyS1 aic &
