#!/bin/bash
if [ "$1" = "remove" ]  ; then
    
    if [[ -d /usr/share/bak.chromium ]]; then
        mv /usr/share/bak.chromium/* /usr/share/chromium
    fi
    if [[ -d /etc/bak.chromium ]]; then
        mv /etc/bak.chromium/* /etc/chromium
    fi
    
fi