#!/bin/bash

set_amixer() {
    # 获取参数
    local card_number="$1"
    local name="$2"
    local value="$3"

    if amixer -c "$card_number" contents | grep -q "$name"; then
        amixer -c "$card_number" cset name="$name" "$value"
    fi
}



set_amixer 0  'LINEOUTL Switch' on
set_amixer 0  'LINEOUTR Switch' on
set_amixer 0  'SPK Switch' on
set_amixer 0  'HPOUT Switch' on
set_amixer 0  'MIC1 Switch' 1

