#!/bin/bash

set -e

git config --global --add safe.directory /usr/lib/walnutpi/Adafruit_Python_PlatformDetect
git config --global --add safe.directory /usr/lib/walnutpi/Adafruit_Blinka

cd /usr/lib/walnutpi
echo "Adafruit_Blinka"
pip3 --no-cache-dir install -e Adafruit_Python_PlatformDetect/ 
pip3 --no-cache-dir install -e Adafruit_Blinka/ 




echo -e "\nready"